export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const START_DOWNLOAD_USERS = 'START_DOWNLOAD_USERS';
export const DOWNLOAD_USERS_SUCCESS = 'DOWNLOAD_USERS_SUCCESS';
export const DOWNLOAD_USERS_ERROR = 'DOWNLOAD_USERS_ERROR';

export const GET_USER_DELETE = 'GET_USER_DELETE';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_ERROR = 'USER_DELETE_ERROR';
